import Image from 'next/image';import Link from 'next/link';import {posts} from '@/lib/site';

const programs=[
  ['Basketball Clinics','Skill-building clinics that teach fundamentals, teamwork and discipline in a fun, supportive environment.','/images/programs/basketball-clinic-real.webp','◉'],
  ['Little Dunk LIVE','Live events that inspire youth through basketball, music, storytelling and positive role models.','/images/team/little-dunk-live-team.webp','♬'],
  ['Mentorship & Education','Mentorship, tutoring and life-skills programs that prepare youth for success in school and life.','/images/programs/mentorship-education.webp','⌂']
];

export default function Home(){return <div className="reference-home">
  <section className="ref-hero"><div className="container ref-hero-grid"><div className="ref-hero-copy"><h1>EMPOWERING YOUTH<br/>THROUGH BASKETBALL,<br/><em>MENTORSHIP</em> & <mark>CREATIVITY</mark></h1><p>We help young people build confidence,<br/>discipline and purpose—on the court<br/>and beyond.</p><div className="ref-buttons"><Link className="purple-btn" href="/programs">Explore Programs&nbsp; →</Link><Link className="outline-btn" href="/contact">Support Our Mission&nbsp; ♡</Link></div></div></div><div className="container ref-trust"><span><Image src="/images/home/trust-icons/shield.webp" alt="" width={38} height={38}/>501(c)(3) Nonprofit</span><span><Image src="/images/home/trust-icons/basketball.webp" alt="" width={38} height={38}/>Basketball · Mentorship · Music</span><span><Image src="/images/home/trust-icons/location.webp" alt="" width={38} height={38}/>Wilmington, Delaware</span></div></section>

  <section className="ref-programs"><div className="container"><div className="ref-heading"><span>WHAT WE DO</span><h2>Programs built to help young people rise</h2></div><div className="ref-program-grid">{programs.map(([title,text,image,icon])=><article key={title}><div className="ref-card-img"><Image src={image} alt={`${title} at Team Dunk`} fill sizes="(max-width:700px) 100vw, 33vw"/></div><div className="ref-card-body"><b className="round-icon">{icon}</b><h3>{title}</h3><p>{text}</p><Link href="/programs">Learn More &nbsp; →</Link></div></article>)}</div></div></section>

  <section className="ref-dunkiverse"><div className="container ref-du-grid"><div className="ref-du-image"><Image src="/images/dunkiverse/dunkiverse-portal-clean.webp" alt="Team Dunk characters entering the glowing Dunkiverse portal" fill sizes="(max-width:800px) 100vw, 55vw"/></div><div><span>THE DUNKIVERSE</span><h2>WHERE BASKETBALL<br/>MEETS IMAGINATION</h2><p>The Dunkiverse is our official Roblox world where youth can explore, play, compete and learn—a safe, positive space built on teamwork, creativity and endless possibilities.</p><Link className="purple-btn" href="/dunkiverse">Enter the Dunkiverse&nbsp; →</Link></div></div></section>

  <section className="ref-impact"><div className="container"><div className="impact-top"><div><span>OUR IMPACT</span><h2>From the court<br/>to the community</h2></div><div className="impact-stat"><div className="impact-art"><Image src="/images/home/impact-youth-cropped.webp" alt="" fill sizes="72px"/></div><strong>—</strong><small>Youth Reached</small></div><div className="impact-stat"><div className="impact-art"><Image src="/images/home/impact-partners-cropped.webp" alt="" fill sizes="72px"/></div><strong>—</strong><small>Community Partners</small></div><div className="impact-stat"><div className="impact-art"><Image src="/images/home/impact-programs-cropped.webp" alt="" fill sizes="72px"/></div><strong>—</strong><small>Programs Delivered</small></div><blockquote><div className="quote-art"><Image src="/images/home/impact-quote-cropped.webp" alt="" fill sizes="58px"/></div>“Team Dunk creates spaces where young people feel seen, supported and inspired to be their best—on the court and in life.”</blockquote></div><div className="ghana-journey"><div><span>LITTLE DUNK LIVE · GHANA 2026</span><h3>We’re going to Ghana!</h3><p>In August 2026, Little Dunk LIVE will travel to Ghana to connect with youth, share skills, inspire dreams and build global friendships through basketball and creativity.</p></div><div className="journey-track"><b>Our Journey to Ghana</b><div className="track"><i/><i/><i/><i/></div><div className="track-labels"><small>Plan</small><small>Prepare</small><small>Travel</small><small>Impact</small></div><Link className="orange-btn" href="/team-dunk-ghana">Follow the Journey&nbsp; →</Link></div></div></div></section>

  <section className="ref-stories"><div className="container"><div className="ref-heading"><span>LATEST STORIES</span><h2>News, stories and inspiration</h2></div><div className="ref-story-grid">{[posts[1],posts[4],posts[0]].map(p=><article key={p.slug}><div><Image src={p.image} alt={p.title} fill sizes="(max-width:700px) 100vw, 33vw"/></div><small>{p.category}</small><h3>{p.title}</h3><p>{p.excerpt}</p><Link href={`/blog/${p.slug}`}>Read More&nbsp; →</Link></article>)}</div></div></section>
  </div>}
