'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {addInquiry,deleteInquiry,fetchInquiries,getSession,isSupabaseConfigured,signIn,signOut,updateInquiry,updateInquiryStatus} from '@/lib/supabase';

const statuses=['new','in_progress','resolved','archived'];
const labels={new:'New',in_progress:'In Progress',resolved:'Resolved',archived:'Archived'};
const blank={name:'',email:'',phone:'',inquiry_type:'general',organization:'',subject:'',message:'',page_source:'/admin',status:'new'};
const fmt=v=>v?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';

export default function AdminPortal(){
 const [boot,setBoot]=useState(true),[auth,setAuth]=useState(false),[items,setItems]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[modal,setModal]=useState(null);
 const load=useCallback(async()=>{setBusy(true);setError('');try{setItems(await fetchInquiries())}catch{setError('Could not load submissions. Check Supabase configuration and policies.')}finally{setBusy(false)}},[]);
 useEffect(()=>{if(!isSupabaseConfigured()){queueMicrotask(()=>setBoot(false));return}getSession().then(s=>{if(s){setAuth(true);load()}}).finally(()=>setBoot(false))},[load]);
 async function login(e){e.preventDefault();setError('');setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget));const r=await signIn(f.email,f.password);setBusy(false);if(!r.ok)return setError(r.error||'Incorrect credentials.');setAuth(true);load()}
 async function logout(){await signOut();setAuth(false);setItems([])}
 async function save(e){e.preventDefault();setBusy(true);try{const f=Object.fromEntries(new FormData(e.currentTarget));modal?.id?await updateInquiry(modal.id,f):await addInquiry(f);setModal(null);await load()}catch{setError('Could not save submission.')}finally{setBusy(false)}}
 async function status(id,value){try{await updateInquiryStatus(id,value);setItems(x=>x.map(i=>i.id===id?{...i,status:value}:i))}catch{setError('Could not update status.')}}
 async function remove(item){if(!confirm(`Delete submission from ${item.name}? This cannot be undone.`))return;try{await deleteInquiry(item.id);setModal(null);load()}catch{setError('Could not delete submission.')}}
 const shown=useMemo(()=>items.filter(i=>(filter==='all'||i.status===filter)&&(!search||`${i.name} ${i.email} ${i.phone} ${i.organization} ${i.subject} ${i.message}`.toLowerCase().includes(search.toLowerCase()))),[items,filter,search]);
 if(boot)return <main className="td-admin boot"><span/></main>;
 if(!isSupabaseConfigured())return <main className="td-admin login"><div className="login-card"><b>TD</b><small>TEAM DUNK ADMIN</small><h1>Setup required</h1><p>Local: add the Supabase URL and publishable key to <code>.env.local</code>. Vercel: add both variables in Project Settings, then redeploy.</p></div></main>;
 if(!auth)return <main className="td-admin login"><form className="login-card" onSubmit={login}><b>TD</b><small>SECURE ADMIN PORTAL</small><h1>Welcome back</h1><p>Sign in with your Supabase admin account.</p><label>Admin email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<em>{error}</em>}<button disabled={busy}>{busy?'Signing in…':'Login to dashboard →'}</button></form></main>;
 return <main className="td-admin shell"><header><div className="admin-brand"><b>TD</b><span><strong>Team Dunk <i>Admin</i></strong><small>INQUIRY MANAGEMENT</small></span></div><nav><button onClick={load}>↻ Refresh</button><button className="primary" onClick={()=>setModal({...blank,mode:'edit'})}>+ Add Entry</button><button onClick={logout}>Log out</button></nav></header><div className="admin-content">{error&&<p className="admin-error">{error}</p>}<section className="admin-stats"><article><span>Total submissions</span><strong>{items.length}</strong></article><article><span>New / unread</span><strong>{items.filter(i=>i.status==='new').length}</strong></article><article><span>Resolved</span><strong>{items.filter(i=>i.status==='resolved').length}</strong></article></section><section className="admin-tools"><input type="search" placeholder="Search name, email, phone, message…" value={search} onChange={e=>setSearch(e.target.value)}/><div>{['all',...statuses].map(s=><button className={filter===s?'active':''} key={s} onClick={()=>setFilter(s)}>{s==='all'?'All':labels[s]}</button>)}</div></section><section className="admin-card"><div className="admin-card-head"><h2>Website inquiries</h2><span>{shown.length} records</span></div>{busy&&<p className="admin-loading">Loading…</p>}<div className="admin-table-wrap"><div className="admin-table"><div className="row head"><span>Name</span><span>Contact</span><span>Type</span><span>Subject / message</span><span>Received</span><span>Status</span><span>Actions</span></div>{!busy&&shown.map(i=><div className="row" key={i.id}><span><b className="avatar">{i.name?.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</b>{i.name}</span><span><a href={`mailto:${i.email}`}>{i.email||'—'}</a><small>{i.phone||'—'}</small></span><span>{i.inquiry_type}</span><span><b>{i.subject||'No subject'}</b><small>{i.message||'—'}</small></span><span>{fmt(i.created_at)}</span><span><select value={i.status} onChange={e=>status(i.id,e.target.value)} className={i.status}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></span><span className="actions"><button onClick={()=>setModal({...i,mode:'detail'})}>Detail</button><button onClick={()=>setModal({...i,mode:'edit'})}>Edit</button><button className="danger" onClick={()=>remove(i)}>Delete</button></span></div>)}{!busy&&!shown.length&&<p className="empty">No submissions found.</p>}</div></div></section></div>{modal&&<AdminModal item={modal} onClose={()=>setModal(null)} onSave={save}/>}</main>
}

function AdminModal({item,onClose,onSave}){const detail=item.mode==='detail';return <div className="admin-modal"><button className="backdrop" onClick={onClose} aria-label="Close"/><form className="modal-panel" onSubmit={onSave}><header><div><small>{detail?'SUBMISSION DETAILS':item.id?'EDIT SUBMISSION':'ADD SUBMISSION'}</small><h2>{item.name||'New inquiry'}</h2></div><button type="button" onClick={onClose}>×</button></header><div className="modal-grid">{[['name','Full name'],['email','Email'],['phone','Phone'],['organization','Organization'],['subject','Subject'],['page_source','Page source']].map(([n,l])=><label key={n}>{l}<input name={n} defaultValue={item[n]||''} readOnly={detail} required={n==='name'}/></label>)}<label>Inquiry type<select name="inquiry_type" defaultValue={item.inquiry_type||'general'} disabled={detail}>{['general','program','volunteer','sponsorship','donation','ghana','event','shop'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select name="status" defaultValue={item.status||'new'} disabled={detail}>{statuses.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></label><label className="full">Message<textarea name="message" rows="6" defaultValue={item.message||''} readOnly={detail}/></label>{detail&&<label className="full">Received<input readOnly value={fmt(item.created_at)}/></label>}</div><footer><button type="button" onClick={onClose}>Close</button>{!detail&&<button className="save">Save submission</button>}</footer></form></div>}
